[profile.default]
slow-timeout = { period = "5s", terminate-after = 1, grace-period = "5s" }
fail-fast = false

[profile.default-miri]
slow-timeout = { period = "60s", terminate-after = 2, grace-period = "5s" }
fail-fast = false
