[package]
name = "uitest"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
proc-macro = true

[dependencies]
glob = "0.3.2"
proc-macro2 = { version = "1.0.95", features = ["span-locations"] }
